name: akarahnet
version: '1.0-SNAPSHOT'
main: akarahnet.Core
api-version: '1.21'
bootstrapper: akarahnet.Bootstrapper

dependencies:
  server:
    plugin-packs:
      load: BEFORE
      required: true
      join-classpath: true