name: akarahnet
version: '1.0-SNAPSHOT'
main: akarahnet.Core
api-version: '1.21'
bootstrapper: akarahnet.Bootstrapper
folia-supported: true

dependencies:
  bootstrap:
    plugin-packs:
      load: BEFORE
      required: true
      join-classpath: true
    actions:
      load: BEFORE
      required: true
      join-classpath: true
  server:
    plugin-packs:
      load: BEFORE
      required: true
      join-classpath: true
    actions:
      load: BEFORE
      required: true
      join-classpath: true